apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teamspace-app-manager
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teamspace-app
  namespace: teamspaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teamspace-app-binding
subjects:
- kind: ServiceAccount
  name: teamspace-app
  namespace: teamspaces
roleRef:
  kind: ClusterRole
  name: teamspace-app-manager
  apiGroup: rbac.authorization.k8s.io 